 # **IMPORTAÇÃO DE BIBLIOTECA**

In [ ]:
import pandas as pd

# **CRIAÇÃO DO PANDAS DATA FRAME**

In [ ]:
dados = pd.read_csv("/content/SAMPLE_ENERGY_DATA.csv")

# **ANÁLISE EXPLORATÓRIA**

In [ ]:
# Visualiar os registros
dados.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-12-01 00:00:00,2026-08-07 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-07 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-07 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-07 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-07 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
# Dimensões do Data Frame
dados.shape

(163943, 9)

In [ ]:
# Verificar as informações do formato dos dados de cada atributo (coluna)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163943 entries, 0 to 163942
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Date                   163943 non-null  object
 1   Time                   163943 non-null  object
 2   Global_active_power    163943 non-null  float64
 3   Global_reactive_power  163943 non-null  float64
 4   Voltage                163943 non-null  float64
 5   Global_intensity       163943 non-null  float64
 6   Sub_metering_1         163943 non-null  int64
 7   Sub_metering_2         163943 non-null  int64
 8   Sub_metering_3         163943 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 11.3+ MB

In [ ]:
# Estatísticas descritivas dos atributos numéricos
# contagem, min, max, media, mediana, desvio padrão, distribuição dos quartis
dados.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,163943.000000,163943.000000,163943.000000,163943.000000,163943.000000,163943.000000,163943.000000
mean,1.093051,0.124073,240.827630,4.633563,1.134236,1.315286,6.480124
std,1.062535,0.112305,3.242136,4.465014,6.202420,5.891517,8.454072
min,0.076000,0.000000,224.870000,0.200000,0.000000,0.000000,0.000000
25%,0.308000,0.048000,238.980000,1.400000,0.000000,0.000000,0.000000
50%,0.600000,0.100000,241.000000,2.600000,0.000000,0.000000,1.000000
75%,1.526000,0.196000,242.880000,6.400000,0.000000,1.000000,17.000000
max,10.290000,1.078000,253.750000,44.600000,83.000000,79.000000,31.000000