In [1]:
import pandas as pd

# Dataset1 - Appliances Energy Prediction (UCI)

 a empresa de eficiência energética está analisando o comportamento de uma residência de baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e observar quais condições de temperatura e umidade estavam presentes nesses momentos.

In [2]:
dados = pd.read_csv('/content/amostra_ex1_energydata_complete.csv')

# 1. Carregue a amostra no Pandas e apresente head(), shape, info() e describe().

In [3]:
dados.head()

   Appliances  lights       T1     RH_1       T2     RH_2       T3     RH_3
0          40       0  20.8900  35.4000  17.7600  39.1633  20.2900  36.9000
1          90      10  21.8900  53.1000  21.2900  45.3600  21.6333  49.2267
2          50       0  21.3900  35.5000  17.6333  40.5300  21.6667  35.2000
3          50       0  21.3900  41.0333  23.8900  34.8400  22.0333  36.9333
4          70       0  19.9633  35.1267  16.4633  40.1267  20.0000  36.4000

In [10]:
print(f'Total de registros: {dados.shape[0]}')
print(f'Total de colunas: {dados.shape[1]}')

Total de registros: 1974
Total de colunas: 8

In [6]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Appliances  1974 non-null   int64
 1   lights      1974 non-null   int64
 2   T1          1974 non-null   float64
 3   RH_1        1974 non-null   float64
 4   T2          1974 non-null   float64
 5   RH_2        1974 non-null   float64
 6   T3          1974 non-null   float64
 7   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 123.5 KB

In [11]:
dados.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,93.044580,3.839919,21.664703,40.219193,20.293635,40.411386,22.231615,39.209733
std,93.826149,7.937076,1.574883,3.971923,2.126958,4.037686,1.957275,3.288818
min,20.000000,0.000000,16.790000,27.733300,16.100000,24.063300,17.200000,30.133300
25%,50.000000,0.000000,20.700000,37.205825,18.790000,37.760000,20.700000,36.900000
50%,60.000000,0.000000,21.600000,39.590000,20.000000,40.433300,22.100000,38.433300
75%,100.000000,0.000000,22.600000,42.991675,21.500000,43.228325,23.290000,41.741250
max,770.000000,50.000000,26.260000,57.496700,28.917500,56.026700,29.198600,49.226700

# 2. Renomeie Appliances para Consumo_Eletrodomesticos e simplifique o nome de pelo menos três atributos ambientais.

In [12]:
dados.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [18]:
dados = dados.rename({'Appliances': 'Consumo_eletrodomesticos',
             'lights':'Temperatura',
              'T1':'Temperatura_1',
              'RH_1': 'Umidade_1',
              'T2':'Temperatura_2',
              'RH_2':'Umidade_2',
              'T3':'Temperatura_3',
              'RH_3':'Umidade_3' }, axis=1)

print(dados.columns)

Index(['Consumo_eletrodomesticos', 'Temperatura', 'Temperatura_1', 'Umidade_1',
       'Temperatura_2', 'Umidade_2', 'Temperatura_3', 'Umidade_3'],
      dtype='object')

# 3. Determine o maior consumo de eletrodomésticos registrado na amostra.

In [19]:
CMAX = dados ["Consumo_eletrodomesticos"].max()
print(f'O consumm máximo de eletrodomésticos foi de {CMAX:.2f} KW')

O consumm máximo de eletrodomésticos foi de 770.00 KW

# 4. Calcule um limiar correspondente a 70% do valor máximo e crie um DataFrame contendo somente os registros acima desse limite.

In [21]:
C70 = CMAX*0.7
print(f'O limiar correspondente a 70% é de {C70:.2f} KW')

O limiar correspondente a 70% é de 539.00 KW

#5. Conte os registros selecionados e calcule qual percentual da amostra eles representam.

# 6. Calcule a temperatura média de T1 e crie outro DataFrame contendo simultaneamente consumo acima de 70% do máximo e temperatura acima da média.

# 7. Compare os dois DataFrames e explique o efeito da inclusão da temperatura como segundo critério.